// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// KeyHandlerFunc turns a function with the right signature into a key handler
type KeyHandlerFunc func(KeyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn KeyHandlerFunc) Handle(params KeyParams) middleware.Responder {
	return fn(params)
}

// KeyHandler interface for that can handle valid key params
type KeyHandler interface {
	Handle(KeyParams) middleware.Responder
}

// NewKey creates a new http.Handler for the key operation
func NewKey(ctx *middleware.Context, handler KeyHandler) *Key {
	return &Key{Context: ctx, Handler: handler}
}

/*Key swagger:route GET /key key

key

*/
type Key struct {
	Context *middleware.Context
	Handler KeyHandler
}

func (o *Key) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewKeyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
