// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "emptyApi/models"
)

// PostOKCode is the HTTP code returned for type PostOK
const PostOKCode int = 200

/*PostOK Success

swagger:response postOK
*/
type PostOK struct {

	/*
	  In: Body
	*/
	Payload *PostOKBody `json:"body,omitempty"`
}

// NewPostOK creates PostOK with default headers values
func NewPostOK() *PostOK {

	return &PostOK{}
}

// WithPayload adds the payload to the post o k response
func (o *PostOK) WithPayload(payload *PostOKBody) *PostOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post o k response
func (o *PostOK) SetPayload(payload *PostOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostDefault Error

swagger:response postDefault
*/
type PostDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostDefault creates PostDefault with default headers values
func NewPostDefault(code int) *PostDefault {
	if code <= 0 {
		code = 500
	}

	return &PostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post default response
func (o *PostDefault) WithStatusCode(code int) *PostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post default response
func (o *PostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post default response
func (o *PostDefault) WithPayload(payload *models.Error) *PostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post default response
func (o *PostDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
